"""Add prayer tracking with float coordinates

Revision ID: 9b1fe4006320
Revises: c30c84431902
Create Date: 2025-12-01 15:41:57.298179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b1fe4006320'
down_revision: Union[str, Sequence[str], None] = 'c30c84431902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prayer_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('last_prayer_date', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_user_streak', 'prayer_streaks', ['user_id', 'current_streak'], unique=False)
    op.create_index(op.f('ix_prayer_streaks_id'), 'prayer_streaks', ['id'], unique=False)
    op.alter_column('prayer_logs', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('prayer_logs', 'on_time',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('prayer_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prayer_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.drop_index(op.f('ix_prayer_logs_completed'), table_name='prayer_logs')
    op.drop_index(op.f('ix_prayer_logs_created_at'), table_name='prayer_logs')
    op.drop_index(op.f('ix_prayer_logs_prayer_date'), table_name='prayer_logs')
    op.drop_index(op.f('ix_prayer_logs_prayer_name'), table_name='prayer_logs')
    op.drop_index(op.f('ix_prayer_logs_user_completed'), table_name='prayer_logs')
    op.drop_index(op.f('ix_prayer_logs_user_date'), table_name='prayer_logs')
    op.drop_index(op.f('ix_prayer_logs_user_id'), table_name='prayer_logs')
    op.drop_constraint(op.f('uix_user_prayer_date'), 'prayer_logs', type_='unique')
    op.create_index('idx_prayer_date_range', 'prayer_logs', ['user_id', 'prayer_date', 'completed'], unique=False)
    op.create_index('idx_user_completed', 'prayer_logs', ['user_id', 'completed'], unique=False)
    op.create_index('idx_user_date', 'prayer_logs', ['user_id', 'prayer_date'], unique=False)
    op.create_unique_constraint('uq_user_prayer_date', 'prayer_logs', ['user_id', 'prayer_name', 'prayer_date'])
    op.alter_column('user_locations', 'calculation_method',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_locations', 'asr_calculation',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.execute("UPDATE user_locations SET updated_at = NOW() WHERE updated_at IS NULL;")
    op.alter_column('user_locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.drop_index(op.f('ix_user_locations_coords'), table_name='user_locations')
    op.create_index('idx_location_coords', 'user_locations', ['latitude', 'longitude'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', name='userrole'),
               nullable=False)
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', name='userrole'),
               nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('idx_location_coords', table_name='user_locations')
    op.create_index(op.f('ix_user_locations_coords'), 'user_locations', ['latitude', 'longitude'], unique=False)
    op.alter_column('user_locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.alter_column('user_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_locations', 'asr_calculation',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_locations', 'calculation_method',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_user_prayer_date', 'prayer_logs', type_='unique')
    op.drop_index('idx_user_date', table_name='prayer_logs')
    op.drop_index('idx_user_completed', table_name='prayer_logs')
    op.drop_index('idx_prayer_date_range', table_name='prayer_logs')
    op.create_unique_constraint(op.f('uix_user_prayer_date'), 'prayer_logs', ['user_id', 'prayer_name', 'prayer_date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_prayer_logs_user_id'), 'prayer_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_prayer_logs_user_date'), 'prayer_logs', ['user_id', 'prayer_date'], unique=False)
    op.create_index(op.f('ix_prayer_logs_user_completed'), 'prayer_logs', ['user_id', 'completed'], unique=False)
    op.create_index(op.f('ix_prayer_logs_prayer_name'), 'prayer_logs', ['prayer_name'], unique=False)
    op.create_index(op.f('ix_prayer_logs_prayer_date'), 'prayer_logs', ['prayer_date'], unique=False)
    op.create_index(op.f('ix_prayer_logs_created_at'), 'prayer_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_prayer_logs_completed'), 'prayer_logs', ['completed'], unique=False)
    op.alter_column('prayer_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.alter_column('prayer_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prayer_logs', 'on_time',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('prayer_logs', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_prayer_streaks_id'), table_name='prayer_streaks')
    op.drop_index('idx_user_streak', table_name='prayer_streaks')
    op.drop_table('prayer_streaks')
    # ### end Alembic commands ###
