"""Create prayer tables

Revision ID: c30c84431902
Revises: b32d77f15ea4
Create Date: 2025-11-30 15:03:14.205597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c30c84431902'
down_revision: Union[str, Sequence[str], None] = 'b32d77f15ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prayer_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prayer_name', sa.String(), nullable=False),
    sa.Column('prayer_date', sa.String(), nullable=False),
    sa.Column('prayer_time', sa.String(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('on_time', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'prayer_name', 'prayer_date', name='uix_user_prayer_date')
    )
    op.create_index(op.f('ix_prayer_logs_completed'), 'prayer_logs', ['completed'], unique=False)
    op.create_index(op.f('ix_prayer_logs_created_at'), 'prayer_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_prayer_logs_id'), 'prayer_logs', ['id'], unique=False)
    op.create_index(op.f('ix_prayer_logs_prayer_date'), 'prayer_logs', ['prayer_date'], unique=False)
    op.create_index(op.f('ix_prayer_logs_prayer_name'), 'prayer_logs', ['prayer_name'], unique=False)
    op.create_index('ix_prayer_logs_user_completed', 'prayer_logs', ['user_id', 'completed'], unique=False)
    op.create_index('ix_prayer_logs_user_date', 'prayer_logs', ['user_id', 'prayer_date'], unique=False)
    op.create_index(op.f('ix_prayer_logs_user_id'), 'prayer_logs', ['user_id'], unique=False)
    op.create_table('user_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('calculation_method', sa.Integer(), nullable=True),
    sa.Column('asr_calculation', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_user_locations_coords', 'user_locations', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_user_locations_id'), 'user_locations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_locations_id'), table_name='user_locations')
    op.drop_index('ix_user_locations_coords', table_name='user_locations')
    op.drop_table('user_locations')
    op.drop_index(op.f('ix_prayer_logs_user_id'), table_name='prayer_logs')
    op.drop_index('ix_prayer_logs_user_date', table_name='prayer_logs')
    op.drop_index('ix_prayer_logs_user_completed', table_name='prayer_logs')
    op.drop_index(op.f('ix_prayer_logs_prayer_name'), table_name='prayer_logs')
    op.drop_index(op.f('ix_prayer_logs_prayer_date'), table_name='prayer_logs')
    op.drop_index(op.f('ix_prayer_logs_id'), table_name='prayer_logs')
    op.drop_index(op.f('ix_prayer_logs_created_at'), table_name='prayer_logs')
    op.drop_index(op.f('ix_prayer_logs_completed'), table_name='prayer_logs')
    op.drop_table('prayer_logs')
    # ### end Alembic commands ###
